// let d = new Date()
// console.log(d)

// get methods

// console.log(d.getDate())
// console.log(d.getMonth())
// console.log(d.getFullYear())
// console.log(d.getHours())
// console.log(d.getMinutes())
// console.log(d.getSeconds())
// console.log(d.getMilliseconds())
// console.log(d.getDay())
// console.log(d.getTime())
// console.log(Date.now())

//  let d = new Date(2026, 1, 1, 10, 10, 10)
//  console.log(d)
// let d = new Date("February 16, 2025 10:10:10")
// console.log(d)
// console.log(d.getMonth())

const d = new Date()
d.setFullYear(2025)
d.setMonth(11)
d.setDate(21)
d.setHours(10)
d.setMinutes(10)
d.setSeconds(10)
d.setMilliseconds(1)
d.setTime(999999999)
console.log(d)